### ISSUE TITLE
Teaser titels cut off

### ISSUE THREAD

**Issue by iznakurnozh** [elan-ev/vallery#7]
label:"User Interface (UI)"

**Problem:**
Longer centered texts on teasers may not be readable:
![grafik](https://user-images.githubusercontent.com/38284875/96249836-179fb200-0fae-11eb-9f86-c223ea1d6a69.png)

**Possible solution:**
Line breaks after smaller amount of characters as it is now.

**Observed behavior on:**
Smartphones and tablets

**Comment by JulianKniephoff** [comment]
These thumbnails are created by Opencast, so there is nothing Vallery can really do here. However, @CGreweling might still want to know about this, being the lernfunk.de admin. :wink:
